package com.lowes.entity.enums;

public enum PhaseType {
    PLANNING_AND_DESIGN,
    DEMOLITION,
    STRUCTURAL_WORK,
    PLUMBING_ROUGH_IN,
    ELECTRICAL_ROUGH_IN,
    HVAC_INSTALLATION,
    INSULATION,
    DRYWALL_INSTALLATION,
    FLOORING,
    TILING,
    CABINETRY_AND_FIXTURES,
    PAINTING,
    DOORS_AND_WINDOWS_INSTALLATION,
    LIGHTING_AND_ELECTRICAL_FIXTURES,
    PLUMBING_FIXTURES,
    FINISH_CARPENTRY,
    CLEANING_AND_WASTE_REMOVAL,
    FINAL_INSPECTION,
    HANDOVER_PROJECT_COMPLETION
}
