package com.lowes.entity.enums;

public enum PhaseType {
    PLANNING_AND_DESIGN,
    STRUCTURAL_WORK,
    HVAC_INSTALLATION,
    FLOORING,
    TILING,
    CARPENTRY,
    PAINTING,
    CABINET_INSTALLATION,
    DOORS_AND_WINDOWS_INSTALLATION,
    ELECTRICITY,
    PLUMBING,
    CLEANING_AND_WASTE_REMOVAL,
}
