package com.lowes.entity.enums;

public enum RenovationType {
    KITCHEN_RENOVATION,
    BATHROOM_RENOVATION,
    LIVING_ROOM_REMODEL,
    BEDROOM_RENOVATION,
    BASEMENT_FINISHING,
    ATTIC_CONVERSION,
    FULL_HOME_RENOVATION,
    EXTERIOR_RENOVATION,
    GARAGE_RENOVATION,
}
