package com.lowes.entity.enums;


public enum RenovationType {
    KITCHEN_RENOVATION,
    BATHROOM_RENOVATION,
    BEDROOM_RENOVATION,
    LIVING_ROOM_RENOVATION,
    WHOLE_HOME,
    BALCONY_RENOVATION,
    FULL_RENOVATION
}
