package com.lowes.entity.enums;

public enum RenovationType {
    KITCHEN_RENOVATION,
    BATHROOM_RENOVATION,
    LIVING_ROOM_REMODEL,
    BEDROOM_RENOVATION,
    BASEMENT_FINISHING,
    ATTIC_CONVERSION,
    FULL_HOME_RENOVATION,
    EXTERIOR_RENOVATION,
    GARAGE_RENOVATION,
    FLOORING_REPLACEMENT,
    ROOF_REPLACEMENT,
    PLUMBING_UPGRADE,
    ELECTRICAL_REWIRING,
    HVAC_INSTALLATION,
    PAINTING_AND_WALL_REPAIR,
    WINDOW_AND_DOOR_REPLACEMENT,
    ENERGY_EFFICIENCY_IMPROVEMENTS,
    SMART_HOME_UPGRADE,
    LANDSCAPE_OUTDOOR_REMODELING,
    STRUCTURAL_REPAIR
}
